feat: Add error handling for cron job setup
docs: Add help text for -r / --raw

fix: Add lowercase attribute to OUTPUT_FORMAT var

diff --git a/pve/get-vm-ips b/pve/get-vm-ips
--- a/pve/get-vm-ips
+++ b/pve/get-vm-ips
@@ -2,7 +2,7 @@
 
 declare -a VMID_LIST
 declare -A IP_LIST
-declare OUTPUT_FORMAT='txt'
+declare -l OUTPUT_FORMAT='raw'
 declare OUTPUT_FILE
 declare VERBOSE=0
 
@@ -12,19 +12,25 @@ debug() {
 
 setup-cron() {
     local cmd
-    printf "Setting up script as a cron job.\n"
+    printf "Setting up script as a cron job...\n"
     if [[ $# -gt 0 ]]; then
         cmd="${BASH_SOURCE[0]} $*"
     else
         cmd="${BASH_SOURCE[0]} -f ansible -o $HOME/generated-hosts.ini"
     fi
+    printf "Command to be added to cron:\n\n\t%s\n\n" "$cmd"
 
     if crontab -l 2>/dev/null | grep -qi "${BASH_SOURCE[0]}"; then
         printf >&2 "Cron job already specified! Use 'crontab -e' and delete the entry before adding a new one.\n"
         return 1
     fi
 
-    { crontab -l 2>/dev/null; printf "* * */1 * * %s\n" "$cmd"; } | crontab -
+    printf "Adding cron job...\n"
+    { crontab -l 2>/dev/null; printf "* * */1 * * %s\n" "$cmd"; } | crontab - || {
+        printf >&2 "[ERROR]: Failed to add cron job!\n"
+        return 1
+    }
+    return 0
 }
 
 if [[ $1 =~ ^(-c|--cron) ]]; then
@@ -38,12 +44,13 @@ fi
 
 while [[ -n $1 && $1 =~ ^- && ! $1 == '--' ]]; do
     case $1 in
+
         -f|--format)
             { [[ -n $2 && ! $2 =~ ^- ]] && shift && OUTPUT_FORMAT=$1; } || {
                 printf >&2 "Bad or missing arguement to: -o | --output-format\n";
                 exit 1;
             }
-            if [[ ! $OUTPUT_FORMAT =~ (ansible|txt|ip|raw) ]]; then
+            if [[ ! ${OUTPUT_FORMAT} =~ (ansible|txt|ip|raw) ]]; then
                 printf >&2 "Output format should be one of: ansible | txt | ip\n"
                 exit 1
             fi
@@ -77,10 +84,13 @@ and write them to a file in a structured format.
 
 OPTIONS:
   -f, --format <fmt>       Output format for the file.
-                             Valid values:
-                               - ansible : INI-style lines (default)
+                             Valid formats:
+                               - ansible : INI-style Ansible lines (default)
                                - raw     : Plain "<hostname> <ip>" format
                                - ip      : Output only "<ip>" format
+
+  -r, --raw                Alias for '-f raw' or '--format raw'.
+                           Outputs in the '<hostname> <ip>' format.  
 
   -o, --outfile <file>     Destination file path to write output to.
                            Writes to stdout by default.  
