perf: Remove unnecessary grep, add brackets to error message tags

diff --git a/prolug/lab-setup/admin-u16-s2 b/prolug/lab-setup/admin-u16-s2
--- a/prolug/lab-setup/admin-u16-s2
+++ b/prolug/lab-setup/admin-u16-s2
@@ -31,26 +31,27 @@ check-disks() {
     local disk_size
     local -a EXTRA_DISKS
     IFS=$'\n' read -r -d '' -a EXTRA_DISKS < <(
-        lsblk | grep -i 'xvd[b-z]' | awk '{ printf "%s ", $1; printf "%s\n", $4}'
+        lsblk | awk '/xvd[b-z]/ { printf "%s ", $1; printf "%s\n", $4}'
     )
+
     # verify that there are at least 3 extra disks
     [[ "${#EXTRA_DISKS[@]}" -ge 3 ]] || {
-        printf >&2 "ERROR:  Bad number of disks.\n" && return 1
+        printf >&2 "[ERROR]:  Bad number of disks.\n" && return 1
     } 
 
-    # verify disk size
+    # verify disk size (3G minimum)
     for disk in "${EXTRA_DISKS[@]}"; do
         [[ -z $disk ]] && continue
         disk_size="$(tr -d '[:alpha:]' <<< "${disk##* }")"
         if (( disk_size < 3 )); then
-            printf >&2 -- "ERROR: Disk: %s -- Does not have 3GB available.\n" "${disk%% *}"
+            printf >&2 -- "[ERROR]: Disk: '%s' does not have 3GB available.\n" "${disk%% *}"
             return 1
         fi
     done
 }
 
 check-disks || {
-    printf >&2 "\nERROR:  Lab verification failed. Encountered a problem with the disks.\n"
+    printf >&2 "\n[ERROR]:  Lab verification failed. Encountered a problem with the disks.\n"
     printf >&2 "\tPlease report this problem to an administrator.\n\n"
     exit 1
 }
