feat(todo): Set up script to accept ssh config file

diff --git a/monitoring/add-ssh-fingerprints b/monitoring/add-ssh-fingerprints
--- a/monitoring/add-ssh-fingerprints
+++ b/monitoring/add-ssh-fingerprints
@@ -5,12 +5,16 @@ declare INVENTORY_FILE
 declare KNOWN_HOSTS="$HOME/.ssh/known_hosts"
 declare -a IPS
 
-process-inventory(){
+process-ansible-inventory(){
     for entry in "${ENTRIES[@]}"; do
         local parsed_ip=
         parsed_ip="$(perl -ne 'print $1 if m/\b(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\b/' <<< "$entry")"
         { [[ -n $parsed_ip ]] && IPS=("${IPS[@]}" "$parsed_ip"); } || continue
     done
+}
+
+process-ssh-config(){
+    : "TODO"
 }
 
 add-fingerprints(){
@@ -46,12 +50,20 @@ while [[ -n $1 && $1 =~ ^- && $1 != '--' ]]; do
             }
             shift;
             ;;
+        -s|--ssh-config)
+            { [[ -n $2 && ! $2 =~ ^- ]] && shift && SSH_CONFIG_FILE=$1; } || {
+                printf >&2 "Bad argument to -s/--ssh-config: %s\n" "$2" && exit 1
+            }
+            ;;
 
         -k|--known-hosts)
             { [[ -n $2 && ! $2 =~ ^- ]] && shift && KNOWN_HOSTS=$1; } || {
-                printf >&2 "Bad argument to -i/--inventory: %s\n" "$2"
+                printf >&2 "Bad argument to -i/--inventory: %s\n" "$2" && exit 1
             }
             shift;
+            ;;
+        -h|--help)
+            : "TODO"
             ;;
         *)
             printf "Unrecognized argument: %s\n" "$1"
@@ -62,13 +74,24 @@ done
 
 [[ $1 == '--' ]] && shift;
 
-INVENTORY_FILE="${INVENTORY_FILE:?No inventory file was provided! Run again with --help for usage.}"
+if [[ -z $INVENTORY_FILE && -z $SSH_CONFIG_FILE ]]; then
+    printf >&2 "No SSH config file or ansible inventory was provided!\n"
+    printf >&2 "See %s --help for usage.\n" "${BASH_SOURCE[0]}"
+    exit 1
+fi
+
+
 
 declare -a ENTRIES
 mapfile -t ENTRIES < "$INVENTORY_FILE"
 
-process-inventory || {
+
+{ [[ -n $INVENTORY_FILE ]] && process-inventory; } || {
     printf >&2 "Failed to process inventory! \n" && exit 1
+}
+
+{ [[ -n $SSH_CONFIG_FILE ]] && process-ssh-config; } || {
+    printf >&2 "Failed to process SSH config file!\n" && exit 1
 }
 
 printf "Inventory processed.\n"
