fix: Add default case when parsing args, exit on unknown arguments

diff --git a/k8s-setup/install-cilium b/k8s-setup/install-cilium
--- a/k8s-setup/install-cilium
+++ b/k8s-setup/install-cilium
@@ -18,6 +18,9 @@ while [[ -n $1 && $1 =~ ^- && $1 != '--' ]]; do
         -i|--ignore-hostname)
             IGNORE_HOSTNAME=1
             ;;
+        *)
+            printf >&2 "[ERROR]: Unknown option: %s\n" "$1"
+            exit 1
     esac
 done
 
