feat(fix): Add overlay kernel module, add ip forwarding to iptables feat(fix): Add containerd repo and installation

diff --git a/haproxy_k8s_keepalived/install-k8s b/haproxy_k8s_keepalived/install-k8s
--- a/haproxy_k8s_keepalived/install-k8s
+++ b/haproxy_k8s_keepalived/install-k8s
@@ -43,15 +43,18 @@ if [[ $OS_FAMILY == *debian* ]]; then
 
     printf "Attempting to add the 'br_netfilter' kernel module.\n"
 	cat <<- 'EOF' | sudo tee /etc/modules-load.d/k8s.conf
+		overlay
 		br_netfilter
 	EOF
 
+    sudo modprobe overlay
     sudo modprobe br_netfilter
 
     printf "Attempting to configure network bridge for iptables.\n"
     cat <<- 'EOF' | sudo tee /etc/sysctl.d/k8s.conf
 		net.bridge.bridge-nf-call-ip6tables = 1
-		net.bridge.bridge-nf-call-iptables = 1
+		net.bridge.bridge-nf-call-iptables  = 1
+		net.ipv4.ip_forward                 = 1
 	EOF
 
     sudo sysctl --system
@@ -81,7 +84,6 @@ if [[ $OS_FAMILY == *rhel* ]]; then
         sudo setenforce 0
         sudo sed -i -E 's/^(SELINUX=)enforcing$/\1permissive/' /etc/selinux/config
     fi
-    :
 
     # install deps
     if ! sudo dnf install -y yum-utils device-mapper-persistent-data lvm2 containerd; then
@@ -135,26 +137,35 @@ if [[ $OS_FAMILY == *rhel* ]]; then
     
 
 
-    printf "Adding 'br_netfilter' kernel module.\n"
+    ##################### Configuration ####################
+    printf "Adding 'br_netfilter' and 'overlay' kernel modules.\n"
     cat <<- 'EOF' | sudo tee /etc/modules-load.d/k8s.conf
+		overlay
 		br_netfilter
 	EOF
+
     if ! sudo modprobe br_netfilter; then
         printf >&2 "modprobe: Unable to load the br_netfilter kernel module.\n"
     fi
 
+    if ! sudo modprobe overlay; then
+        printf >&2 "modprobe: Unable to load the br_netfilter kernel module.\n"
+    fi
 
-    printf "Configuring iptables network bridge\n"
+
+    printf "Configuring iptables network bridge and enabling IP forwarding.\n"
 	cat <<- 'EOF' | sudo tee /etc/sysctl.d/k8s.conf
 		net.bridge.bridge-nf-call-ip6tables = 1
-		net.bridge.bridge-nf-call-iptables = 1
+		net.bridge.bridge-nf-call-iptables  = 1
+		net.ipv4.ip_forward                 = 1
 	EOF
 
-    printf "Reloading kernel modules.\n"
+    printf "Reloading kernel parameters.\n"
     if ! sudo sysctl --system; then
         printf "Unable to reload kernel modules!\n" && exit 1
     fi
 
+    # add bash completion for kubectl
     if rpm -qa | grep -i 'bash-completion'; then
         printf "Bash-completion is on the system. Adding completion for Kubernetes.\n"
         source <(kubectl completion bash)
@@ -166,13 +177,57 @@ if [[ $OS_FAMILY == *rhel* ]]; then
         printf "Added completion for Kubernetes.\n"
     fi
 
-    # open ports 6443 and 10250 in firewalld
+    # Open necessary ports in firewalld
     if [[ $(sudo systemctl is-active firewalld) == 'active' ]]; then
-        printf "Opening ports 6443 and 10250 in firewalld.\n"
-        sudo firewall-cmd --add-port 6443/tcp --permanent
-        sudo firewall-cmd --add-port 10250/tcp --permanent
-        sudo firewall-cmd --reload
+        printf "Opening necessary ports in firewalld.\n"
+        case $(hostname) in 
+            *control*|*master*)
+                sudo firewall-cmd --permanent --add-port={6443,2379,2380,10250,10251,10252,10257,10259,179}/tcp
+                sudo firewall-cmd --permanent --add-port=4789/udp
+                sudo firewall-cmd --add-masquerade --permanent
+                sudo firewall-cmd --reload
+                ;;
+            *worker*)
+                sudo firewall-cmd --permanent --add-port={179,10250,30000-32767}/tcp
+                sudo firewall-cmd --permanent --add-port=4789/udp
+                sudo firewall-cmd --add-masquerade --permanent
+                sudo firewall-cmd --reload
+                ;;
+            *)
+        esac
     fi
+
+    printf "Adding the Docker-ce repository for containerd.\n"
+
+    # Install containerd
+    # if ! sudo dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo; then
+    #     printf "There was a problem when downloading the Docker repository!\n" && exit 1
+    # fi
+
+    if ! sudo curl -fsSL -o /etc/yum.repos.d/docker-ce.repo \
+        https://download.docker.com/linux/rhel/docker-ce.repo; then
+        printf "There was a problem when downloading the Docker repository!\n" && exit 1
+    fi
+
+    printf "Configuring containerd...\n"
+    if ! containerd config default | sudo tee /etc/containerd/config.toml > /dev/null 2>&1; then
+        printf "Error while setting up default configuration for containerd!\n" && exit 1
+    fi
+
+    printf "Restarting and enabling containerd...\n"
+
+    if ! sudo systemctl restart containerd; then
+        printf "There was a problem restarting containerd.\n"
+    fi
+
+    if ! sudo systemctl enable --now containerd; then
+        printf "There was a problem enabling containerd.\n"
+    fi
+
+    if ! sudo systemctl status containerd; then
+        printf "Could not verify the status of containerd!\n"
+    fi
+
 
 fi
 
