feat(keepalived): Print errors to stderr

diff --git a/haproxy_k8s_keepalived/install-keepalived b/haproxy_k8s_keepalived/install-keepalived
--- a/haproxy_k8s_keepalived/install-keepalived
+++ b/haproxy_k8s_keepalived/install-keepalived
@@ -102,17 +102,39 @@ add-config-file() {
     }
 }
 
+restart-and-enable() {
+    sudo systemctl restart keepalived || {
+        printf >&2 'Failed to restart keepalived.\n' && return 1; 
+    }
+
+    sudo systemctl enable --now keepalived || {
+        printf >&2 'Failed to enable keepalived.\n' && return 1; 
+    }
+}
+
 install-keepalived-debian() {
     if ! sudo apt update && sudo apt-get install keepalived -y ; then
-        printf "Failed to install keepalived.\n" && return 1
+        printf >&2 "Failed to install keepalived.\n" && return 1
     fi
+    add-config-file || {
+        printf >&2 "Failed to add keepalived configuration file.\n" && return 1
+    }
+    restart-and-enable || {
+        printf >&2 "Failed to restart and enable keepalived.\n" && return 1
+    }
     return 0
 }
 
 install-keepalived-rhel() {
     if ! sudo dnf install keepalived -y; then
-        printf "Failed to install keepalived via dnf.\n" && return 1
+        printf >&2 "Failed to install keepalived via dnf.\n" && return 1
     fi
+    add-config-file || {
+        printf >&2 "Failed to add keepalived configuration file.\n" && return 1
+    }
+    restart-and-enable || {
+        printf >&2 "Failed to restart and enable keepalived.\n" && return 1
+    }
     return 0
 }
 
@@ -129,15 +151,17 @@ fi
 
 if [[ $OS_FAMILY == *rhel* ]]; then
     install-keepalived-rhel || {
-        printf "Failed to install keepalived!\n" && exit 1
+        printf >&2 "Failed to install keepalived!\n" && exit 1
     }
+    printf "\033[31mSuccessfully installed keepalived.\n\033[0m"
     exit 0
 fi
 
 if [[ $OS_FAMILY == *debian* ]]; then
     install-keepalived-debian || {
-        printf "Failed to install keepalived!\n" && exit 1
+        printf >&2 "Failed to install keepalived!\n" && exit 1
     }
+    printf "\033[31mSuccessfully installed keepalived.\n\033[0m"
     exit 0
 fi
 
