feat(cilium): Add error handling to installation script

diff --git a/haproxy_k8s_keepalived/install-cilium b/haproxy_k8s_keepalived/install-cilium
--- a/haproxy_k8s_keepalived/install-cilium
+++ b/haproxy_k8s_keepalived/install-cilium
@@ -1,19 +1,37 @@
 #!/bin/bash
 
-mkdir -p /tmp/cilium-install
-cd /tmp/cilium-install || {
-    printf "Couldn't switch directory to /tmp/cilium-install\n" && exit 1
+install-cilium() {
+
+    mkdir -p /tmp/cilium-install || {
+        printf >&2 "Unable to create temporary directory: /tmp/cilium-install\n" && return 1
+    }
+    cd /tmp/cilium-install || {
+        printf >&2 "Couldn't switch directory to /tmp/cilium-install\n" && return 1
+    }
+
+    curl -LO https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz || {
+        printf >&2 "Problem downloading cilium tarball.\n" && return 1
+    }
+
+    tar -xzvf /tmp/cilium-install/cilium-linux-amd64.tar.gz || {
+        printf >&2 "Problem extracting cilium tarball.\n" && return 1
+    }
+
+    sudo cp /tmp/cilium-install/cilium /usr/local/bin || {
+        printf >&2 "Problem copying cilium binary to /usr/loca/bin\n" && return 1
+    }
+
+    rm -rf /tmp/cilium-install || {
+        printf >&2 "Failed to remove cilium install directory.\n" && return 1
+    }
+
+    { [[ -f /usr/local/bin/cilium ]] && which cilium; } && {
+        printf "Successfully added cilium to PATH.\n"
+    }
+    return 0
 }
 
-curl -LO https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz
-tar -xzvf /tmp/cilium-install/cilium-linux-amd64.tar.gz
-sudo cp /tmp/cilium-install/cilium /usr/local/bin
-
-[[ -f /usr/local/bin/cilium ]] && which cilium && {
-    printf "Successfully added cilium to PATH.\n"
-}
-
-rm -rf /tmp/cilium-install || {
-    printf "Failed to remove cilium install directory.\n"
-}
+if ! install-cilium; then
+    printf >&2 "Problem installing cilium.\n"
+fi
 
