feat: Add warn and err functions for formatting, declare file at top

diff --git a/misc/prolug/het-stream-cmd-executor b/misc/prolug/het-stream-cmd-executor
--- a/misc/prolug/het-stream-cmd-executor
+++ b/misc/prolug/het-stream-cmd-executor
@@ -1,4 +1,7 @@
 #!/bin/bash
+# shellcheck disable=SC2120
+
+declare WATCH_FILE="/data/stream_write/stream_answers"
 
 declare -a EXCLUDE_KEYWORDS=(
     'rm -rf /'
@@ -13,7 +16,6 @@ declare -a EXCLUDE_KEYWORDS=(
     '\u001b'
 )
 
-
 declare -A COLORS=(
     [red]=$'\033[31m'
     [green]=$'\033[32m'
@@ -21,32 +23,37 @@ declare -A COLORS=(
     [reset]=$'\033[0m'
 )
 
-# Directory to watch
-WATCH_FILE="/data/stream_write/stream_answers"
+warn() {
+    [[ $# -gt 0 ]] && printf "[ %sWARNING%s ]: %s\n" "${COLORS[yellow]}" "${COLORS[reset]}" "$*" && return 0
+    printf "[ %sWARNING%s ]: " "${COLORS[yellow]}" "${COLORS[reset]}"
+}
+
+err() {
+    [[ $# -gt 0 ]] && printf "[ %sERROR%s ]: %s\n" "${COLORS[red]}" "${COLORS[reset]}" "$*" && return 0
+    printf "[ %sERROR%s ]: " "${COLORS[red]}" "${COLORS[reset]}" 
+}
 
 is-forkbomb() {
-    local CMD
+    local CMD=
     local PARSED=
     [[ -z $1 ]] && printf "No input provided to function!\n" && return 0
     CMD="$1"
     PARSED=$(
         perl -ne 'print $1 if m/(.{1,}\s*\(\s*\)\s*[{]\s*.{1,}\s*[|]\s*.{1,}\s*&\s*[}]).*/' <<< "$CMD"
     )
+
     printf "Parsed command: %s\n" "$PARSED"
     [[ -z $PARSED ]] && return 1
     [[ -n $PARSED ]] && printf "Forkbomb detected in '%s' -- This part: %s\n" \
         "${COLORS[red]}${CMD}${COLORS[reset]}" \
         "${COLORS[green]}${PARSED}${COLORS[reset]}" && return 0
-
 }
 
 
 is-malicious-cmd() {
-    # return true (0) if cmd is malicious
     local CMD
     [[ -z $1 ]] && printf "No input provided to function!\n" && return 0
     CMD="$1"
-
     is-forkbomb "$CMD" && return 0
 
     [[ "${EXCLUDE_KEYWORDS[*]}" =~ ${CMD} ]] &&
@@ -57,13 +64,12 @@ is-malicious-cmd() {
         printf "Illegal character(s) found in command %s: %s\n" "$CMD" "${BASH_REMATCH[1]}" &&
         return 0
 
-    # extra layer of check (for control seqs)
+    # extra layer for control seqs
     for EX in "${EXCLUDE_KEYWORDS[@]}"; do
         [[ $CMD =~ ${EX} ]] &&
             printf "Illegal substring found in command %s: %s\n" "$CMD" "$EX" &&
             return 0
     done
-
     return 1
 }
 
@@ -71,17 +77,17 @@ is-malicious-cmd() {
 main() {
     # Watch for events (create, modify, delete, etc.)
     while read -r _; do
-
         local -a LINE=()
+
         mapfile -d : -t LINE < <(tail -n 1 "${WATCH_FILE}")
         user="${LINE[0]}"
         source="${LINE[1]}"
         command="${LINE[2]}"
 
         printf "User: %s answered on %s. Their command is: %s\n" \
-                "${COLORS[green]}$user${COLORS[reset]}" \
-                "${COLORS[green]}$source${COLORS[reset]}]" \
-                "${COLORS[yellow]}$command${COLORS[reset]}"
+                "${COLORS[green]}${user}${COLORS[reset]}" \
+                "${COLORS[green]}${source}${COLORS[reset]}]" \
+                "${COLORS[yellow]}${command}${COLORS[reset]}"
 
         # Select a server to use
         num=$(( (RANDOM % 5) + 15 ))
@@ -107,10 +113,10 @@ main() {
 }
 
 if ! type inotifywait > /dev/null 2>&1; then
-    printf "The inotify-tools package is not installed!\n" && exit 1;
+    err; printf >&2 "The inotify-tools package is not installed! Exiting.\n" && exit 1;
 fi
 
 main || {
-    printf >&2 "Script encountered error!\n" && exit 1
+    err; printf >&2 "Script encountered an error! Exiting.\n" && exit 1;
 }
 
