feat: Add arg parsing for cloud image, template name, and vmid

diff --git a/pve/tf-deployment/create-template b/pve/tf-deployment/create-template
--- a/pve/tf-deployment/create-template
+++ b/pve/tf-deployment/create-template
@@ -1,4 +1,5 @@
 #!/bin/bash
+# shellcheck disable=SC2120
 # Create a VM template that is cloud-init ready for Proxmox VE
 # Written by Connor W. (https://github.com/kolkhis)
 
@@ -15,7 +16,43 @@ if [[ $EUID -ne 0 ]]; then
     exit 1
 fi
 
-create-rocky10-template(){
+declare TEMPLATE_IMAGE="/var/lib/vz/template/qcow/Rocky-10-GenericCloud-Base.latest.x86_64.qcow2"
+declare TEMPLATE_NAME="/var/lib/vz/template/qcow/Rocky-10-GenericCloud-Base.latest.x86_64.qcow2"
+declare -i VMID=100
+
+while [[ -n $1 && $1 =~ ^- ]]; do
+    [[ $1 == '--' ]] && break
+    case $1 in
+        -i|--image)
+            if [[ -n $2 && ! $2 =~ ^- && -f $2 ]]; then
+                shift
+                TEMPLATE_IMAGE="$1"
+            else
+                err 'Bad or missing argument to -i|--image.'
+                exit 1
+            fi
+            shift;
+            ;;
+        -n|--name)
+            if [[ -n $2 && ! $2 =~ ^- ]]; then
+                shift
+                TEMPLATE_NAME="$1"
+            fi
+            shift
+            ;;
+        -v|--vmid)
+            if [[ -n $2 && ! $2 =~ ^- ]]; then
+                shift
+                VMID="$2"
+            fi
+            shift
+            ;;
+        *)
+            ;;
+    esac
+done
+
+create-uefiboot-template(){
     local -i vmid=9030
     local -i mem=2048
     local -i cores=1
@@ -24,6 +61,22 @@ create-rocky10-template(){
     local template_name="rocky-10-cloudinit-template"
     local template_image="/var/lib/vz/template/qcow/Rocky-10-GenericCloud-Base.latest.x86_64.qcow2"
     local cputype="host"
+
+    while [[ -n $1 && $1 =~ ^- ]]; do
+        case $1 in
+            -i|--image) 
+                [[ -n $2 && -f $2 ]] && shift && template_image="$1"
+                shift
+                ;;
+            -n|--name)
+                [[ -n $2 ]] && shift && template_name="$1"
+                ;;
+            -v|--vmid)
+                [[ -n $2 ]] && shift && vmid="$1"
+                shift
+                ;;
+        esac
+    done
 
     if ! [[ -f $template_image ]]; then
         err "Template image does not exist: $template_image"
@@ -56,8 +109,8 @@ create-rocky10-template(){
     printf "[INFO]: Convert new VM to a template when ready by running: qm template %d\n" "$vmid"
 }
 
-create-rocky10-template || {
-    err "Failed to create Rocky 10 template."
+create-uefiboot-template -i "$TEMPLATE_IMAGE" -n "$TEMPLATE_NAME" -v "$VMID" || {
+    err "Failed to create Proxmox template."
     exit 1
 }
 
