feat: Add special files to chroot dir

diff --git a/airgap/setup-chroot-jail b/airgap/setup-chroot-jail
--- a/airgap/setup-chroot-jail
+++ b/airgap/setup-chroot-jail
@@ -70,8 +70,20 @@ setup-chroot-dir() {
 
     done
 
-    printf "Creating the chroot directory (%s)\n" "${CHROOT_DIR}"
     # [[ ! -d /var/chroot ]] && sudo mkdir -p /var/chroot
+    if ! [[ -d /var/chroot ]]; then
+        printf "Directory not found.\n"
+        printf "Creating the chroot directory (%s)\n" "${CHROOT_DIR}"
+    fi
+
+    # Create special files
+    printf "Making special files.\n"
+    
+    mknod -m 666 "${CHROOT_DIR}/dev/null" c 1 3 || { :;}
+    mknod -m 666 "${CHROOT_DIR}/dev/tty" c 5 0 || { :;}
+    mknod -m 666 "${CHROOT_DIR}/dev/zero" c 1 5 || { :;}
+    mknod -m 666 "${CHROOT_DIR}/dev/random" c 1 8 || { :;}
+    mknod -m 666 "${CHROOT_DIR}/dev/urandom" c 1 9 || { :;}
 
 }
 
