feat: Add function to add chrootdirectory entry in sshd_config

diff --git a/airgap/setup-chroot-jail b/airgap/setup-chroot-jail
--- a/airgap/setup-chroot-jail
+++ b/airgap/setup-chroot-jail
@@ -118,18 +118,58 @@ setup-jailed-user() {
         printf >&2 "Failed to add jailed user account!\n" && return 1
     }
     printf "User account %s succussfully added.\n" "$JAILED_USER"
-    local PASSWORD=
-    read -r -s -p "Enter password for user account: " PASSWORD
 
-    # TODO: test
-    printf "%s\n%s\n" "$PASSWORD" "$PASSWORD" | passwd "${JAILED_USER}"
+    local PASSWORD=
+    read -r -s -p "Enter password for user account: " PASSWORD || {
+        printf >&2 "Failed to read password for user: %s\n" "$JAILED_USER"
+    }
+
+    printf "Setting password for user: %s\n" "${JAILED_USER}"
+    printf "%s\n%s\n" "$PASSWORD" "$PASSWORD" | sudo passwd "${JAILED_USER}" || {
+        printf >&2 "Failed to set password for user: %s\n" "$JAILED_USER" && return 1
+    }
+
+}
+
+configure-ssh(){
+    # Set up the bastion script and rules for the jailed user
+    if ! grep -qi "Match User ${JAILED_USER}" /etc/ssh/sshd_config; then
+        sudo sed -i -E "\$a Match User ${JAILED_USER}\nChrootDirectory ${CHROOT_DIR}\n" \
+            /etc/ssh/sshd_config || {
+            printf >&2 "Failed to add entry for user in /etc/ssh/sshd_config!\n" && return 1
+        }
+        printf "Added ChrootDirectory rule for %s\n" "$JAILED_USER"
+    else
+        printf "Entry already found in /etc/ssh/sshd_config. Skipping.\n"
+    fi
+
+    printf "Restarting SSH daemon...\n"
+
+    sudo systemctl restart ssh || {
+        printf >&2 "Failed to restart SSH!\n" && return 1
+    }
 
 }
 
     
-printf "Setting up chroot jail environment.\n"
+printf "Setting up chroot jail environment in: %s\n" "$CHROOT_DIR"
 setup-chroot-dir || {
-    printf >&2 "Failed to set up chroot directory!\n"
+    printf >&2 "Failed to set up chroot directory!\n" && exit 1
 }
-printf "\033[32mSuccessfully set up chroot directory.\033[0m\n"
+printf "\033[32mSuccessfully set up chroot directory in %s\033[0m\n" "$CHROOT_DIR"
+
+printf "Attempting to set up a user account for jailed user: %s\n" "$JAILED_USER"
+setup-jailed-user || {
+    printf >&2 "Failed to set up jailed user!\n" && exit 1
+}
+printf "\033[32mSuccessfully set up jailed user: %s\033[0m\n" "$JAILED_USER"
+
+
+printf "Attempting to configure SSH rules for jailed user.\n"
+configure-ssh || {
+    printf >&2 "Failed to configure ssh rules for jailed user!\n" && exit 1
+}
+printf "\033[32mSuccessfully set up jailed user.\033[0m\n"
+
+
 
