refactor: Use a variable for ssh config file in setup-chroot-jail
fix: Check 2nd arg for '-' while parsing CLI args

refactor: Use lowercase variable names in for loops

feat: Add -S/--ssh-config-file CLI option

diff --git a/airgap/setup-chroot-jail b/airgap/setup-chroot-jail
--- a/airgap/setup-chroot-jail
+++ b/airgap/setup-chroot-jail
@@ -28,6 +28,7 @@ declare BASTION_HOST_IP='192.168.4.74'
 declare BASTION_SCRIPT='bastion.sh'
 declare LOG_FILE='./chroot-setup.log'
 declare DESTINATIONS_OUTPUT_FILE="$CHROOT_DIR/destinations.txt"
+declare SSH_CONFIG_FILE="$HOME/.ssh/config"
 
 # exec > "$LOG_FILE"
 
@@ -38,7 +39,7 @@ declare -a BINARIES=(
     "logger"
 )
 
-declare -a SYSFILES=(
+declare -a SYSTEM_FILES=(
     "/etc/passwd"
     "/etc/group"
     "/etc/nsswitch.conf"
@@ -94,13 +95,24 @@ while [[ -n $1 ]]; do
             VERBOSE=1
             shift;
             ;;
-        -s|--script)
-            [[ -n $2 ]] && shift && BASTION_SCRIPT=$2 || printf >&2 "No valid argument passed to -s/--script\n"
+        -s|--bastion-script)
+            { [[ -n $2 && ! $2 =~ ^-  ]] && shift && BASTION_SCRIPT=$1; } || {
+                err; printf >&2 "No valid argument passed to -s/--script\n"; }
+            shift;
             ;;
+
+        -S|--ssh-config-file)
+            { [[ -n $2 && ! $2 =~ ^- ]] && shift && SSH_CONFIG_FILE=$1; } || {
+                err; printf >&2 "The --ssh-config-file option was given but no argument was specified.\n"
+            }
+            shift;
+            ;;
+
         -h|--help)
             # TODO(docs): Add help text
             :
             ;;
+
         *)
             printf "Invalid argument: %s\n" "$1"
             shift;
@@ -129,28 +141,28 @@ setup-chroot-dir() {
 
     printf "Copying system files.\n"
 
-    for SYSFILE in "${SYSFILES[@]}"; do
-        printf "Copying system file: %s\n" "$SYSFILE"
+    for sysfile in "${SYSTEM_FILES[@]}"; do
+        printf "Copying system file: %s\n" "$sysfile"
 
-        if [[ ! -d  "${CHROOT_DIR}$(dirname "$SYSFILE")" ]]; then
-            printf "Creating directory for %s at %s\n" "$SYSFILE" "$CHROOT_DIR/$(basename "$SYSFILE")"
-            sudo mkdir -p "$(dirname "$SYSFILE")" || {
+        if [[ ! -d  "${CHROOT_DIR}$(dirname "$sysfile")" ]]; then
+            printf "Creating directory for %s at %s\n" "$sysfile" "$CHROOT_DIR/$(basename "$sysfile")"
+            sudo mkdir -p "$(dirname "$sysfile")" || {
                 err;
-                printf >&2 "Failed to make directory for %s at %s\n" "$SYSFILE" "$(dirname "$SYSFILE")"
+                printf >&2 "Failed to make directory for %s at %s\n" "$sysfile" "$(dirname "$sysfile")"
             }
         fi
 
-        printf "Copying system file %s to %s\n" "$SYSFILE" "${CHROOT_DIR}$SYSFILE"
-        sudo cp "$SYSFILE" "${CHROOT_DIR}${SYSFILE}"
+        printf "Copying system file %s to %s\n" "$sysfile" "${CHROOT_DIR}$sysfile"
+        sudo cp "$sysfile" "${CHROOT_DIR}${sysfile}"
 
     done
 
     # Copy over binaries and their linked libraries
-    for BINARY in "${BINARIES[@]}"; do
-        debug "Copying binary: ${BINARY}"
-        BIN_PATH=$(which "$BINARY")
+    for binary in "${BINARIES[@]}"; do
+        debug "Copying binary: ${binary}"
+        BIN_PATH=$(which "$binary")
         sudo cp "$BIN_PATH" "${CHROOT_DIR}${BIN_PATH}" || {
-            err; printf >&2 "Failed to copy binary '%s' to destination: %s\n" "$BINARY" "${CHROOT_DIR}${BIN_PATH}"
+            err; printf >&2 "Failed to copy binary '%s' to destination: %s\n" "$binary" "${CHROOT_DIR}${BIN_PATH}"
         }
 
         # Gather Link Libraries for the binary
@@ -159,7 +171,7 @@ setup-chroot-dir() {
             # perl -ne 'print "$1\n" if s/^[^\/]*(\/.*)\s*\(.*$/\1/')
 
         for LLIB in "${BIN_LLIBS[@]}"; do
-            debug "LLIB for $BINARY - ${LLIB}"
+            debug "LLIB for $binary - ${LLIB}"
             if ! stat "${CHROOT_DIR}${LLIB}" > /dev/null 2>&1; then
                 sudo cp "${LLIB}" "${CHROOT_DIR}${LLIB}" || {
                     err; printf >&2 "Failed to copy linked library '%s' to destination: %s" \
@@ -176,22 +188,22 @@ setup-chroot-dir() {
 
     # Create special files
     printf "Making character special files.\n"
-    for SPECIAL_FILE in "${SPECIAL_FILES[@]}"; do
-        if [[ ! -c "${CHROOT_DIR}${SPECIAL_FILE}" ]]; then
+    for special_file in "${SPECIAL_FILES[@]}"; do
+        if [[ ! -c "${CHROOT_DIR}${special_file}" ]]; then
             local -a MAJOR_MINOR=()
 
             read -r -d '' -a MAJOR_MINOR < <(
-                awk '/Device type/ {print $(NF)"\n"}' < <(stat "$SPECIAL_FILE") | tr ',' ' '
+                awk '/Device type/ {print $(NF)"\n"}' < <(stat "$special_file") | tr ',' ' '
             ) 
 
-            debug "$SPECIAL_FILE - Major: ${MAJOR_MINOR[0]}, Minor: ${MAJOR_MINOR[1]}"
+            debug "$special_file - Major: ${MAJOR_MINOR[0]}, Minor: ${MAJOR_MINOR[1]}"
 
-            sudo mknod -m 666 "${CHROOT_DIR}${SPECIAL_FILE}" c "${MAJOR_MINOR[@]}" || { 
-                err; printf >&2 "Failed to create character special file: %s\n" "${SPECIAL_FILE}";
+            sudo mknod -m 666 "${CHROOT_DIR}${special_file}" c "${MAJOR_MINOR[@]}" || { 
+                err; printf >&2 "Failed to create character special file: %s\n" "${special_file}";
             }
 
         else
-            debug "Character special file already exists: ${CHROOT_DIR}${SPECIAL_FILE}"
+            debug "Character special file already exists: ${CHROOT_DIR}${special_file}"
         fi
     done
 
@@ -252,7 +264,6 @@ configure-user-shell(){
 configure-ssh(){
 
     # Set up the bastion script and rules for the jailed user
-
     if ! grep -qi "Match User ${JAILED_USER}" /etc/ssh/sshd_config; then
         {
 	    cat <<- EOF | sudo tee -a /etc/ssh/sshd_config > /dev/null 2>&1
@@ -281,8 +292,8 @@ configure-ssh(){
 }
 
 parse-ssh-file() {
-    if [[ -f ~/.ssh/config && -f ./generate-destinations ]]; then
-        ./generate-destinations -f ~/.ssh/config -o "$DESTINATIONS_OUTPUT_FILE" || {
+    if [[ -f $SSH_CONFIG_FILE && -f ./generate-destinations ]]; then
+        ./generate-destinations -f "$SSH_CONFIG_FILE" -o "$DESTINATIONS_OUTPUT_FILE" || {
             printf >&2 "Error in destination generation script!\n" && return 1
         }
     else
